spring:
  datasource:
    url: jdbc:postgresql://theater-service-rds-endpoint:5432/booking_platform
    username: theater-service_db_username
    password: theater-service_db_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
