replicaCount: 3

image:
  repository: bookingapp-docker-repo/theatre-service
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
