server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    path: /var/log/myapp/

# Logstash configuration
logstash:
   enabled: false
#   host: logstash-host
#   port: 5044

# ELK stack integration
# spring:
#   elk:
#     enabled: true
#     elasticsearch:
#       rest:
#         uris: http://elasticsearch-host:9200
#         connection-timeout: 3s
#         read-timeout: 3s
#     logstash:
#       host: logstash-host
#       port: 5044
#     kibana:
#       host: http://kibana-host:5601

# Metrics and tracing configuration
# spring:
#   sleuth:
#     enabled: true
#     sampler:
#       probability: 1.0
#   zipkin:
#     base-url: http://zipkin-host:9411
#     enabled: true

# Grafana configuration
grafana:
  dashboards:
    enabled: true
    path: /etc/grafana/dashboards

# Custom configuration for metrics
metrics:
  tags:
    application: myapp
  export:
    prometheus:
      enabled: true
      step: 1m

# Filebeat configuration for logging
# filebeat:
#   inputs:
#     - type: log
#       enabled: true
#       paths:
#         - /var/log/myapp/*.log
#   output:
#     logstash:
#       hosts: ["logstash-host:5044"]

##spring:
##  datasource:
##    url: jdbc:postgresql://theaterservice-rds-endpoint:5432/booking_platform
##    username: theaterservice_db_username
##    password: theaterservice_db_password
##  jpa:
##    properties:
##      hibernate:
##        dialect: org.hibernate.dialect.PostgreSQLDialect
##    hibernate:
##      ddl-auto: update
##  elk:
##    enabled: true
##    elasticsearch:
##      rest:
##        uris: http://elasticsearch-host:9200
##        connection-timeout: 3s
##        read-timeout: 3s
##    logstash:
##      host: logstash-host
##      port: 5044
##    kibana:
##      host: http://kibana-host:5601
##  sleuth:
##    enabled: true
##    sampler:
##      probability: 1.0
#
## Actuator and Prometheus configuration
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,prometheus
#  endpoint:
#    health:
#      show-details: always
#  metrics:
#    export:
#      prometheus:
#        enabled: true
#
## Logging configuration
##logging:
##  level:
##    root: INFO
##    org.springframework.web: DEBUG
##  file:
##    path: /var/log/myapp/
#
## Logstash configuration
##logstash:
##  enabled: true
##  host: logstash-host
##  port: 5044
#
## Metrics and tracing configuration
##zipkin:
##  base-url: http://zipkin-host:9411
##  enabled: true
#
## Grafana configuration
##grafana:
##  dashboards:
##    enabled: true
##    path: /etc/grafana/dashboards
#
## Custom configuration for metrics
##metrics:
##  tags:
##    application: myapp
##  export:
##    prometheus:
##      enabled: true
##      step: 1m
#
## Filebeat configuration for logging
##filebeat:
##  inputs:
##    - type: log
##      enabled: true
##      paths:
##        - /var/log/myapp/*.log
##  output:
##    logstash:
##      hosts: ["logstash-host:5044"]
